SET FOREIGN_KEY_CHECKS = 0; 
DROP TABLE Account_Data;
DROP TABLE Admin;
DROP TABLE Allocations;
DROP TABLE Budgeting;
DROP TABLE Lab_Requirements;
DROP TABLE Leader_Module;
DROP TABLE Lab_Timetable;
DROP TABLE Modules;
DROP TABLE Module_Leaders;
DROP TABLE Notifications;
DROP TABLE Pay_Data;
DROP TABLE Pending_Swaps;
DROP TABLE PHD_Availability;
DROP TABLE PHD_Students;
DROP TABLE Status_Definitions;
DROP TABLE Supervisors;
DROP TABLE Swaps;
DROP TABLE Tech_Staff;
DROP TABLE Time_Slots;
DROP TABLE Week_Date;
DROP TABLE Work_Experience;
SET FOREIGN_KEY_CHECKS = 1; 